platform :ios, '9.0'
target 'WYCloudReadingApp' do

  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'SVProgressHUD'
  pod 'IQKeyboardManager'
  pod 'Masonry'
  pod 'SGPagingView'

use_frameworks!

end 
